name = "specfun"
version = "0.1.0"
license = "MIT"
author = "Rodrigo Castro"
maintainer = "rodpcastro18@gmail.com"
copyright = "Copyright 2025, Rodrigo Castro"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
test-drive = {git = "https://github.com/fortran-lang/test-drive.git" }
